name: 'Creatorland SxT Auth v4'
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: creatorland/public-repo-test-action@main
        with:
          sxt-auth-secret: ${{ secrets.W3_SECRET_DEMO_CREATORLAND_SECRET }}
          sxt-endpoint-url:
            ${{ secrets.W3_SECRET_DEMO_CREATORLAND_ENDPOINT_URL }}
